name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
        with:
          entrypoint: captain-vuetify
      - name: Build
        run: npm build
        with:
          entrypoint: captain-vuetify
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: captain-vuetify
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAPTAIN_A48AF }}'
          channelId: live
          projectId: captain-a48af
